config/routes.rb
Rails.application.routes.draw do
    root 'sessions#home'

    get '/signup' => 'users#new'
    post '/signup' => 'users#create'

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    post '/logout' => 'sessions#destroy'

    post 'plants/search' => 'plants#search', as: 'plants_search'
    
    resources :gardens
    resources :plants
    resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
    belongs_to :user
    belongs_to :plant
end

app/models/plant.rb
class Plant < ApplicationRecord
    has_many :gardens
    has_many :users, through: :gardens
end

app/models/user.rb
class User < ApplicationRecord
    has_many :gardens
    has_many :plants, through: :gardens

    validates :username, :email, presence: true
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    private 

    def log_in(user)
        session[:user_id] = user.id 
    end 

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!session[:user_id]
    end

    def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
    end

end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

    def index
        @plants = Plant.all
    end

    def show
        @plant = Plant.find_by(id: params(:id))
    end

    def new
    end

    def create
        user = current_user
        plant = Plant.find_or_create_by(params[:plant_id])
    end
    
    def search

    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def home
    end

    def create
        user = User.find_by(username: params[:user][:username])
        if user && user.authenticate(params[:user][:password])
          log_in(user)
          redirect_to user_path(user)
        else
          flash[:message] = "Incorrect login info, please try again"
          redirect_to '/login'
        end
    end

    def destroy
        session.clear
        redirect_to root_path
    end

    private

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            log_in(@user)
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar">
    <li id="search_partial"> <%= render '/search_plants'%>
    <%= link_to "Home", '/' %>
    <%= link_to "Plants", plants_path %>
    <%= link_to "Gardens", '/' %>
    <% if logged_in?%>
        <%= link_to "Profile", '/' %>
        <%= link_to "Log out", logout_path, method: "delete" %>
    <% else %>
        <%=link_to "Sign Up", signup_path %> |
        <%=link_to "Log In", login_path %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>GardenPlanner</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <div class="border"></div>

        <div class="header">
            <h1>Garden Builder</h1>
            <p></p>
        </div>

        <div class="container">
            <%= render "layouts/navbar" %>
        </div>

        <div>
            <% if flash[:message] %>
                <%= flash[:message]%>
            <% end %>
            <%= @error%>
        </div>

        <%= yield %>

        <div class="content">

        </div>

        <div class="footer">
            <h2>Garden Builder 2021</h2>
        </div>
    </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user, url:'/signup') do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>
    <br> 

        <br>
    <%= f.label :email %>
    <%= f.email_field :email, required: true %>
    <br> 

        <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br> 

        <br>
    <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h1>Show</h1>